[theme]
base = "light"
primaryColor = "#18181b"
backgroundColor = "#f4f4f5"
secondaryBackgroundColor = "#ffffff"
textColor = "#18181b"
borderColor = "#e4e4e7"
baseRadius = "medium"

[client]
toolbarMode = "minimal"
